### ISSUE TITLE
Projects have iOS 7.1 as target

### ISSUE THREAD

**Issue by jimcremer** [editorscut/ec006-ios7-apps#3]
If people don't have 7.1 (beta, at the moment) installed, the only "run" option in Xcode will be "iOS device."  No simulator options will be available. Though it's easy to change target to 7.0, yielding simulator options,  this could be a mysterious roadblock for beginners.

7.1 betas are not available to all the people who might use the book (like some in my class - the univ.'s student Dev license doesn't include betas).  Again, it's easy for me to tell people to modify the projects but just sending in case you want to do it here at the source.

**Comment by editorscut** [comment]
Arggh - thank you - I hadn't thought of that. As I write books I tend to use the version of the OS I think will be available when the book ships - but here I am releasing betas.

Thank you James,

Daniel

**Comment by dimsumthinking** [comment]
Now that iOS 7.1 has shipped, this should be resolved. Thank you again.
