### ISSUE TITLE
p. 84 - Foornote directs reader to chapter 05TheModel/ directory rather than 06ViewControllers

### ISSUE THREAD

**Issue by boboblee** [editorscut/ec006-ios7-apps#5]
Footnote at bottom of page 84 (first page of chapter 6) directs reader to files in chapter 5 directory - the same message that is on page 61 (first page of chapter 5).

**Comment by dimsumthinking** [comment]
Thank you. I have corrected this. When we push the next version this correction will appear.

Thank you again for your help.
